name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Restart PHP & Nginx
        run: |
          cd /home/server/web
          docker compose restart php nginx