name: Auto Deploy Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy to Server
        run: |
          echo "Masuk ke folder project"
          cd /srv/apps/php-docker-ci-cd-lab

          echo "Simpan commit lama untuk rollback"
          CURRENT_COMMIT=$(git rev-parse HEAD)
          echo $CURRENT_COMMIT > .last_commit_backup

          echo "Ambil update terbaru"
          git fetch origin

          echo "Deploy commit terbaru"
          git reset --hard origin/main

          echo "Bersihkan file tidak terpakai"
          git clean -fd

          echo "Deploy selesai tanpa restart docker"
